<a href="https://colab.research.google.com/github/ShubhamP1028/DeepLearningTute/blob/main/Pract1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Write a program to implement perceptrons in multiclass classification

In [2]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

data = load_wine()
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [5]:
x = data.data
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [6]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
scaler = StandardScaler()
scaler


StandardScaler()

In [8]:
x_scaled = scaler.fit_transform(x)
x_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.25, random_state=42)
x_train, x_test, y_train, y_test

(array([[ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
          0.78858745,  1.39514818],
        [-1.13720713, -0.23011443, -2.43634632, ...,  1.37126518,
          0.49197446, -0.11748635],
        [-0.71721705,  1.87939396,  1.32865481, ..., -0.16430337,
          0.71796531, -1.21613669],
        ...,
        [ 1.70390229, -0.4186237 ,  0.0492855 , ...,  1.06415147,
          0.54847218,  2.54793491],
        [-0.38369551, -0.72382916, -0.38935541, ...,  0.01119018,
         -0.77922407, -0.8021525 ],
        [-0.81603824,  0.10202093,  0.34171277, ..., -0.69078402,
          1.08520045, -0.98366865]]),
 array([[ 7.89806212e-01,  6.85501974e-01,  7.07246859e-01,
         -1.28970717e+00,  1.14155847e+00,  6.48764240e-01,
          1.00469996e+00, -1.54592178e+00,  1.21070982e-01,
          1.81290590e-02,  1.11901785e-02,  1.05695159e+00,
          3.12420304e-01],
        [ 1.49390724e+00,  1.52930533e+00,  2.68605950e-01,
         -1.78652700e-01,  7.90491768e-01,  8.

In [13]:
n_features = x.shape[1]
n_features

13

Binary Perceptron

In [14]:
class percepton:
  def _inti_(self, learning_rate=0.01, epochs=1000):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.weights = np.zeros(n_features+1)   # +1 for bias term

  def predict(self, x):
    x_bias = np.insert(x, 0, 1, axis=1)    # add bias term
    linear_output = np.dot(x_bias, self.weights)
    return np.where(linear_output >= 0, 1, 0)

  def train(self, x, y):
    x_bias = np.insert(x, 0, 1, axis=1)
    for _ in range(self.epochs):
      for xi, target in zip(x_bias, y):
        output = np.dot(xi, self.weights)
        prediction = 1 if output >= 0 else 0
        error = target - prediction
        self.weights += self.learning_rate * error * xi

Multiclass perceptron : Using One vs All

In [ ]:
class multiclassperceptron:
  def _init_ (self, n_features, lr = 0.01, epochs=1000):
    self.models = [Perceptron(lr, epochs) for _ in range(3)]
  def

In [1]:
!git config --global user.email "shubham30p@gmail.com"

In [2]:
!git config --global user.name "ShubhamP1028"

In [3]:
!git clone https://github.com/ShubhamP1028/DeepLearningTute.git

Cloning into 'DeepLearningTute'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [4]:
%cd DeepLearningTute

/content/DeepLearningTute


In [5]:
!cp /content/Pract1.ipynb /content/DeepLearningTute/

cp: cannot stat '/content/Pract1.ipynb': No such file or directory


In [7]:
!git add Pract1.ipynb

fatal: pathspec 'Pract1.ipynb' did not match any files


In [8]:
%cd ..

/content


In [9]:
!dir

DeepLearningTute  sample_data


In [10]:
!cp /content/Pract1.ipynb /content/DeepLearningTute/

cp: cannot stat '/content/Pract1.ipynb': No such file or directory
